services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: is_curs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - is_curs_pgdata:/var/lib/postgresql/data

volumes:
  is_curs_pgdata:
